name: gallery_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Localization
  intl: ^0.17.0

  #BLOC
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  
  #Network
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1

  #Photo
  photo_manager: ^1.2.1
  video_player: ^2.1.5
  cached_network_image: ^3.0.0

  #Google
  google_sign_in: ^5.0.2
  image_picker: ^0.7.4

  path: any
  loading_overlay: ^0.3.0

  cupertino_icons: ^1.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
 #Lint Rules
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:  
    - assets/icon/empty_icon.png